Adding support for AWS/EC2Spot
ivx/yet-another-cloudwatch-exporter pull request #256
Opened 2020-10-04 10:36 UTC by singhjagmohan1000

`discovery:
  exportedTagsOnMetrics:
    ec2Spot: 
      - name
  jobs:
    - type: ec2Spot
      regions:
        - us-west-2
      addCloudwatchTimestamp: true
      period: 300
      length: 300
      awsDimensions:
      - FleetRequestId
      - InstanceType
      metrics:
        - name: FulfilledCapacity
          statistics:
            - Average`

2020-10-06 06:44 UTC, vishalraina commented
/LGTM
Please update README.md with example

2020-10-06 17:03 UTC, ankitgupta0910 commented
LGTM. Thanks for including this.

2020-10-08 14:58 UTC, thomaspeitz commented on aws_cloudwatch.go
> +	if err != nil &&  service != "tgwa"  {
Not quite why you added spaces here.

2020-10-08 14:59 UTC, thomaspeitz commented on aws_tags.go
> +}
Could you please add a  newline here?

2020-10-08 14:59 UTC, thomaspeitz commented on main.go
> +		"ec2Spot",
This is sorted by char (could you please resort)? :)

2020-10-08 14:59 UTC, thomaspeitz commented on README.md
> +  * ec2Spot - Elastic Compute Cloud for Spot Instances
Please sort this list. Thanks!

2020-10-08 15:00 UTC, thomaspeitz requested changes
Looks awesome. Thanks a lot. Could you fix the small issues. Then i release this tomorrow.

2020-10-08 23:32 UTC, singhjagmohan1000 commented
@thomaspeitz I have made the changes as per review comments.

2020-10-12 21:08 UTC, thomaspeitz requested changes
Found some unsorted items. Would you be so kind? :))

Sorry took longer than expected to rereview that.

2020-10-12 21:08 UTC, thomaspeitz commented on aws_cloudwatch.go
> +		"ec2Spot":               "AWS/EC2Spot",
Could you sort this as well please?

2020-10-12 21:08 UTC, thomaspeitz commented on aws_tags.go
> +	case "ec2Spot":
This should be sorted as well please.

2020-10-18 09:00 UTC, singhjagmohan1000 commented
@thomaspeitz Thanks for the feedback. I will sort as per comments. But right now I am facing several other issues with Yace.
https://github.com/ivx/yet-another-cloudwatch-exporter/issues/264 This is one of the issue, that right now I am dealing with. If you have some insights, how we can solve that. That would be helpful.

2020-12-02 10:58 UTC, thomaspeitz commented
Hey @singhjagmohan1000 would really love to merge this :) Could you please resort? Would like to add this to next release.

Beside that #264 is I think fixed in another PR which will be released as well this week.

2020-12-07 07:25 UTC, singhjagmohan1000 commented
@thomaspeitz I am submitting my changes with resorting, now

2020-12-07 07:32 UTC, singhjagmohan1000 commented
@thomaspeitz changes submitted

2020-12-16 13:22 UTC, haarchri commented
can we see this feature in next release ?

2021-01-05 10:10 UTC, merged

2021-01-05 10:10 UTC, thomaspeitz commented
Thanks a lot :)